### ISSUE TITLE
Unable to install bdshare using pip

### ISSUE THREAD

**Issue by mehedino** [rochi88/bdshare#3]
I receive this error in my terminal when I input the command to install:

mehedino@Mehedis-MacBook-Air ~ % pip install bdshare
Collecting bdshare
  Using cached bdshare-0.3.1.tar.gz (9.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xm/8ry6wwvs46j571rz9wjfrmyh0000gn/T/pip-install-w8uyijj8/bdshare_d15ac9ca74284ed092dc03a6ce97d804/setup.py", line 8, in <module>
          with open('CHANGELOG.md') as history_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rochi88** [comment]
fixed on [2d76972](https://github.com/rochi88/bdshare/commit/2d7697272e44421a2fb23aa185f8e17b2a81c0a9)
