### ISSUE TITLE
pe funtion not working 

### ISSUE THREAD

**Issue by supermaxlol** [rochi88/bdshare#6]
pe funtion not working 

from bdshare import get_latest_pe
import pandas as pd

def test_get_latest_pe():
    try:
        # Fetch the latest P/E data
        pe_data = get_latest_pe()
        
        if pe_data is None:
            print("No data received from get_latest_pe()")
            return
        
        # Display the fetched data
        print("Latest P/E Data:")
        print(pe_data)
        
        # Optionally, save the data to a CSV file
        df = pd.DataFrame(pe_data)
        df.to_csv("latest_pe_data.csv", index=False)
        print("Data saved to latest_pe_data.csv")
        
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Run the test
test_get_latest_pe()
 used this code to test on google colab 
shows error msg An unexpected error occurred: 'NoneType' object has no attribute 'find_all'

**Comment by rochi88** [comment]
@supermaxlol please check the new update

**Comment by supermaxlol** [comment]
<img width="1403" alt="Screenshot 2024-07-29 at 2 41 46 AM" src="https://github.com/user-attachments/assets/e9d8ced0-9289-413f-9cc0-fd7b21f4d165">
Now i keep getting, An error occurred: list index out of range

**Comment by rochi88** [comment]
issue should be solved now
